"""
Execution plan model.

Represents the workflow generated by the Planner.
The Execution Manager consumes this plan and executes each task.
"""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from app.models.task import Task


class ExecutionPlan(BaseModel):
    """Represents a workflow generated by the Planner."""

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid",
    )

    id: str = Field(
        ...,
        description="Unique identifier for the execution plan.",
    )

    objective: str = Field(
        ...,
        description="Overall objective of the workflow.",
    )

    tasks: list[Task] = Field(
        default_factory=list,
        description="Ordered list of tasks to execute.",
    )

    planner_notes: str = Field(
        default="",
        description="Additional notes from the planner.",
    )

    version: int = Field(
        default=1,
        ge=1,
        description="Execution plan version.",
    )

    created_at: datetime = Field(
        default_factory=datetime.now,
        description="Timestamp when the plan was created.",
    )